# Set nginx base image
FROM nginx:1.21.1

#Add a user with name nonroot
RUN useradd -ms /bin/bash nonroot

#COPY docker-entrypoint.sh /
#ENTRYPOINT ["/docker-entrypoint.sh"]

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
COPY redirect.conf /etc/nginx/redirect.conf
COPY nginx-csp-header.conf /etc/nginx/nginx-csp-header.conf

# Append "daemon off;" to the beginning of the configuration
# in order to avoid an exit of the container
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

#Run Container as nonroot
#USER nonroot

# Expose ports
#EXPOSE 443

# Define default command
CMD service nginx start